// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: jqHMejC8dcPyddaS4gmqUt
// Component: 8uRuDIsw_Axd

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { PlasmicHead } from "@plasmicapp/react-web";
import { NavigationBar } from "@plasmicpkgs/plasmic-nav";
import { Reveal } from "@plasmicpkgs/react-awesome-reveal";

import { useScreenVariants as useScreenVariantsv6JzT4AzP0Fn } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: v6jzT4azP0Fn/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: jqHMejC8dcPyddaS4gmqUt/projectcss
import sty from "./PlasmicHomepage.module.css"; // plasmic-import: 8uRuDIsw_Axd/css

import Twitter2SvgrepoComsvgIcon from "./icons/PlasmicIcon__Twitter2SvgrepoComsvg"; // plasmic-import: cV4cuMllBGg8/icon
import TelegramSvgrepoComsvgIcon from "./icons/PlasmicIcon__TelegramSvgrepoComsvg"; // plasmic-import: p8ya4hJMYEbR/icon
import GitbookSvgrepoComsvgIcon from "./icons/PlasmicIcon__GitbookSvgrepoComsvg"; // plasmic-import: 5vLE0s1yfrCg/icon

createPlasmicElementProxy;

export type PlasmicHomepage__VariantMembers = {};
export type PlasmicHomepage__VariantsArgs = {};
type VariantPropType = keyof PlasmicHomepage__VariantsArgs;
export const PlasmicHomepage__VariantProps = new Array<VariantPropType>();

export type PlasmicHomepage__ArgsType = {};
type ArgPropType = keyof PlasmicHomepage__ArgsType;
export const PlasmicHomepage__ArgProps = new Array<ArgPropType>();

export type PlasmicHomepage__OverridesType = {
  root?: Flex__<"div">;
  pageMetadataOverride?: Flex__<typeof PlasmicHead>;
  navigationBar?: Flex__<typeof NavigationBar>;
  h5?: Flex__<"h5">;
  h2?: Flex__<"h2">;
};

export interface DefaultHomepageProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicHomepage__RenderFunc(props: {
  variants: PlasmicHomepage__VariantsArgs;
  args: PlasmicHomepage__ArgsType;
  overrides: PlasmicHomepage__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsv6JzT4AzP0Fn()
  });

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <PlasmicHead
            data-plasmic-name={"pageMetadataOverride"}
            data-plasmic-override={overrides.pageMetadataOverride}
            className={classNames("__wab_instance", sty.pageMetadataOverride)}
            description={
              "Otter World is a comprehensive DeFi platform integrating cutting-edge technology and AI to provide a seamless and secure experience. Join us and be a part of our vibrant community!"
            }
            image={"/plasmic/otterworld/images/otterwalletpng.png"}
            title={"Otter World"}
          />

          <div className={classNames(projectcss.all, sty.freeBox__eo8H0)}>
            <div className={classNames(projectcss.all, sty.freeBox__rGyS7)}>
              <NavigationBar
                data-plasmic-name={"navigationBar"}
                data-plasmic-override={overrides.navigationBar}
                brand={
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      sty.link__kugtq
                    )}
                    component={Link}
                    href={"#"}
                    platform={"nextjs"}
                  >
                    <PlasmicImg__
                      alt={"otter logo"}
                      className={classNames(sty.img__z2Kzs)}
                      displayHeight={"52px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      src={{
                        src: "/plasmic/otterworld/images/textOtterworldpng.png",
                        fullWidth: 4000,
                        fullHeight: 2667,
                        aspectRatio: undefined
                      }}
                    />
                  </PlasmicLink__>
                }
                className={classNames("__wab_instance", sty.navigationBar)}
                closeButton={
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img___8AfW)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"none"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    src={"https://static1.plasmic.app/close.svg"}
                  />
                }
                itemsGap={24}
                menuItems={
                  <React.Fragment>
                    <PlasmicLink__
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link__sW0DJ
                      )}
                      component={Link}
                      href={"/"}
                      platform={"nextjs"}
                    >
                      <Twitter2SvgrepoComsvgIcon
                        className={classNames(projectcss.all, sty.svg__upSgn)}
                        role={"img"}
                      />
                    </PlasmicLink__>
                    <PlasmicLink__
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link___8Q603
                      )}
                      component={Link}
                      href={"/"}
                      platform={"nextjs"}
                    >
                      <TelegramSvgrepoComsvgIcon
                        className={classNames(projectcss.all, sty.svg__fSkf4)}
                        role={"img"}
                      />
                    </PlasmicLink__>
                    <PlasmicLink__
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link__aAOl2
                      )}
                      component={Link}
                      href={"/"}
                      platform={"nextjs"}
                    >
                      <GitbookSvgrepoComsvgIcon
                        className={classNames(projectcss.all, sty.svg__ztyoT)}
                        role={"img"}
                      />
                    </PlasmicLink__>
                  </React.Fragment>
                }
                openButton={
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img___2Ee0E)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"none"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    src={"https://static1.plasmic.app/menu.svg"}
                  />
                }
                responsiveBreakpoint={768}
              />
            </div>
          </div>
          <section className={classNames(projectcss.all, sty.section__xWoaY)}>
            <div className={classNames(projectcss.all, sty.freeBox__d0IEh)}>
              <PlasmicImg__
                alt={""}
                className={classNames(sty.img___8Sf1Q)}
                displayHeight={"auto"}
                displayMaxHeight={"none"}
                displayMaxWidth={"none"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"auto"}
                loading={"lazy"}
                src={{
                  src: "/plasmic/otterworld/images/cloud1Png.png",
                  fullWidth: 3000,
                  fullHeight: 1500,
                  aspectRatio: undefined
                }}
              />

              <div className={classNames(projectcss.all, sty.freeBox___5SCng)}>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img___5I3HI)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "100%"
                      : "60%"
                  }
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/otterworld/images/textOtterworldpng.png",
                    fullWidth: 4000,
                    fullHeight: 2667,
                    aspectRatio: undefined
                  }}
                />

                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__eejl1)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "100%"
                      : "50%"
                  }
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/otterworld/images/characterpng.png",
                    fullWidth: 1828,
                    fullHeight: 1828,
                    aspectRatio: undefined
                  }}
                />

                <div
                  className={classNames(projectcss.all, sty.freeBox___26MAq)}
                >
                  <h5
                    data-plasmic-name={"h5"}
                    data-plasmic-override={overrides.h5}
                    className={classNames(
                      projectcss.all,
                      projectcss.h5,
                      projectcss.__wab_text,
                      sty.h5
                    )}
                  >
                    {"Learn More"}
                  </h5>
                </div>
              </div>
              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__sgmcb)}
                displayHeight={"auto"}
                displayMaxHeight={"none"}
                displayMaxWidth={"none"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"auto"}
                loading={"lazy"}
                src={{
                  src: "/plasmic/otterworld/images/cloud2Png.png",
                  fullWidth: 3000,
                  fullHeight: 1500,
                  aspectRatio: undefined
                }}
              />
            </div>
          </section>
          <section className={classNames(projectcss.all, sty.section__n5Zyj)}>
            <div className={classNames(projectcss.all, sty.columns__pm2Hj)}>
              <div className={classNames(projectcss.all, sty.column__xOouk)}>
                <Reveal
                  className={classNames("__wab_instance", sty.reveal__ha3Pu)}
                  direction={"left"}
                  effect={"slide"}
                  triggerOnce={true}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__buigq)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/otterworld/images/pp1Compng.png",
                      fullWidth: 1000,
                      fullHeight: 1000,
                      aspectRatio: undefined
                    }}
                  />
                </Reveal>
              </div>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column__aFmQv)}
              >
                <Reveal
                  className={classNames("__wab_instance", sty.reveal__zr45J)}
                  direction={"right"}
                  effect={"slide"}
                  triggerOnce={true}
                >
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__rdpup)}
                  >
                    <h1
                      className={classNames(
                        projectcss.all,
                        projectcss.h1,
                        projectcss.__wab_text,
                        sty.h1__jvXnT
                      )}
                    >
                      {"What is Otter?"}
                    </h1>
                    <h4
                      className={classNames(
                        projectcss.all,
                        projectcss.h4,
                        projectcss.__wab_text,
                        sty.h4__ht320
                      )}
                    >
                      {
                        "Otter World is a next-gen DeFi platform designed to make decentralized finance accessible and user-friendly. With innovative tools like the Otter Wallet, Otter Guard, and Otter Swap, Otter World empowers users to securely manage, trade, and protect their digital asset. all within an ecosystem that's easy to navigate, even for newcomers to the crypto space."
                      }
                    </h4>
                  </Stack__>
                </Reveal>
              </Stack__>
            </div>
          </section>
          <section className={classNames(projectcss.all, sty.section___1Nyr)}>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__bejzL)}
            >
              <h4
                className={classNames(
                  projectcss.all,
                  projectcss.h4,
                  projectcss.__wab_text,
                  sty.h4___2Tkk8
                )}
              >
                {"Ecosystem"}
              </h4>
              <h1
                className={classNames(
                  projectcss.all,
                  projectcss.h1,
                  projectcss.__wab_text,
                  sty.h1__h1Pan
                )}
              >
                {"Otter Kingdom"}
              </h1>
            </Stack__>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns___7VoMb)}
            >
              <div className={classNames(projectcss.all, sty.column___6PRnW)}>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__fo1Hq)}
                >
                  <h3
                    className={classNames(
                      projectcss.all,
                      projectcss.h3,
                      projectcss.__wab_text,
                      sty.h3__bJo6L
                    )}
                  >
                    {"Otter Wallet"}
                  </h3>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__pCxql
                    )}
                  >
                    {
                      "A secure, all-in-one DeFi wallet that simplifies asset management. Log in with just an email and enjoy seamless access to storing, swapping, and investing in crypto without the hassle of managing seed phrases."
                    }
                  </div>
                </Stack__>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__b0TL)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/otterworld/images/mockup1Png.png",
                    fullWidth: 2000,
                    fullHeight: 2000,
                    aspectRatio: undefined
                  }}
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__wnu6A)}>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__xcCgp)}
                >
                  <h3
                    className={classNames(
                      projectcss.all,
                      projectcss.h3,
                      projectcss.__wab_text,
                      sty.h3__drfQq
                    )}
                  >
                    {"Otter Guard"}
                  </h3>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__oN0NJ
                    )}
                  >
                    {
                      "Your personal DeFi security system. Powered by AI, Otter Guard monitors transactions, detects threats, and ensures that your assets remain safe in the unpredictable world of decentralized finance."
                    }
                  </div>
                </Stack__>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__wWp9)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/otterworld/images/character3Croppng.png",
                    fullWidth: 1000,
                    fullHeight: 1000,
                    aspectRatio: undefined
                  }}
                />
              </div>
              <div className={classNames(projectcss.all, sty.column___6FahF)}>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__rjmfP)}
                >
                  <h3
                    className={classNames(
                      projectcss.all,
                      projectcss.h3,
                      projectcss.__wab_text,
                      sty.h3__wxCO
                    )}
                  >
                    {"Otter Wallet"}
                  </h3>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___1CcQx
                    )}
                  >
                    {
                      "An intuitive token exchange platform that allows you to swap various cryptocurrencies directly from your Otter Wallet. With Otter Swap, diversify your holdings and explore new opportunities in the DeFi space effortlessly."
                    }
                  </div>
                </Stack__>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__yem5D)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/otterworld/images/mockup2Croppng.png",
                    fullWidth: 1000,
                    fullHeight: 1000,
                    aspectRatio: undefined
                  }}
                />
              </div>
            </Stack__>
          </section>
          <section className={classNames(projectcss.all, sty.section__wr0Su)}>
            <div className={classNames(projectcss.all, sty.columns__nyKw5)}>
              <div className={classNames(projectcss.all, sty.column__ubVAy)}>
                <Reveal
                  className={classNames("__wab_instance", sty.reveal__okjq4)}
                  direction={"left"}
                  effect={"slide"}
                  triggerOnce={true}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__pNhdt)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/otterworld/images/characterpng.png",
                      fullWidth: 1828,
                      fullHeight: 1828,
                      aspectRatio: undefined
                    }}
                  />
                </Reveal>
              </div>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column__dhmxm)}
              >
                <Reveal
                  className={classNames("__wab_instance", sty.reveal__ejAfj)}
                  direction={"right"}
                  effect={"slide"}
                  triggerOnce={true}
                >
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__oJtPr)}
                  >
                    <h2
                      data-plasmic-name={"h2"}
                      data-plasmic-override={overrides.h2}
                      className={classNames(
                        projectcss.all,
                        projectcss.h2,
                        projectcss.__wab_text,
                        sty.h2
                      )}
                    >
                      {"Essential Features"}
                    </h2>
                    <Stack__
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__lKZM)}
                    >
                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img___1Nwv6)}
                        displayHeight={"52px"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"52px"}
                        loading={"lazy"}
                        src={{
                          src: "/plasmic/otterworld/images/asset3Img1Png.png",
                          fullWidth: 62,
                          fullHeight: 58,
                          aspectRatio: undefined
                        }}
                      />

                      <Stack__
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__k0RpO
                        )}
                      >
                        <h4
                          className={classNames(
                            projectcss.all,
                            projectcss.h4,
                            projectcss.__wab_text,
                            sty.h4__qBkqr
                          )}
                        >
                          {"Otter Guild"}
                        </h4>
                        <h6
                          className={classNames(
                            projectcss.all,
                            projectcss.h6,
                            projectcss.__wab_text,
                            sty.h6__gUl7Z
                          )}
                        >
                          {
                            "A community-based platform with a leveling system that rewards active participation. Unlock different levels such as Iron, Silver, Gold, Mythril, and Adamantium for exclusive perks and benefits."
                          }
                        </h6>
                      </Stack__>
                    </Stack__>
                    <Stack__
                      as={"div"}
                      hasGap={true}
                      className={classNames(
                        projectcss.all,
                        sty.freeBox___54E4O
                      )}
                    >
                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img__dgzl9)}
                        displayHeight={"52px"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"52px"}
                        loading={"lazy"}
                        src={{
                          src: "/plasmic/otterworld/images/asset3Img1Png.png",
                          fullWidth: 62,
                          fullHeight: 58,
                          aspectRatio: undefined
                        }}
                      />

                      <Stack__
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          sty.freeBox___36Vij
                        )}
                      >
                        <h4
                          className={classNames(
                            projectcss.all,
                            projectcss.h4,
                            projectcss.__wab_text,
                            sty.h4__n9KHd
                          )}
                        >
                          {"Launchpad"}
                        </h4>
                        <h6
                          className={classNames(
                            projectcss.all,
                            projectcss.h6,
                            projectcss.__wab_text,
                            sty.h6__mH96R
                          )}
                        >
                          {
                            "A gateway to early access to the most promising projects in the DeFi space. Invest in the future with our strategic platform designed to propel you to the forefront of innovation."
                          }
                        </h6>
                      </Stack__>
                    </Stack__>
                    <Stack__
                      as={"div"}
                      hasGap={true}
                      className={classNames(
                        projectcss.all,
                        sty.freeBox___5Uz12
                      )}
                    >
                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img__zf1Hl)}
                        displayHeight={"52px"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"52px"}
                        loading={"lazy"}
                        src={{
                          src: "/plasmic/otterworld/images/asset3Img1Png.png",
                          fullWidth: 62,
                          fullHeight: 58,
                          aspectRatio: undefined
                        }}
                      />

                      <Stack__
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__adAd2
                        )}
                      >
                        <h4
                          className={classNames(
                            projectcss.all,
                            projectcss.h4,
                            projectcss.__wab_text,
                            sty.h4___0RRl6
                          )}
                        >
                          {"Lucky Draw"}
                        </h4>
                        <h6
                          className={classNames(
                            projectcss.all,
                            projectcss.h6,
                            projectcss.__wab_text,
                            sty.h6__v0Lv9
                          )}
                        >
                          {
                            "Participate in the Wheel of Fortune events like the Lucky Draw, where you have the chance to win valuable tokens and assets. It's a fun and exciting way to engage with the Otter community while potentially gaining significant rewards."
                          }
                        </h6>
                      </Stack__>
                    </Stack__>
                    <Stack__
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__nhUz4)}
                    >
                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img__kcccC)}
                        displayHeight={"52px"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"52px"}
                        loading={"lazy"}
                        src={{
                          src: "/plasmic/otterworld/images/asset3Img1Png.png",
                          fullWidth: 62,
                          fullHeight: 58,
                          aspectRatio: undefined
                        }}
                      />

                      <Stack__
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__nGof9
                        )}
                      >
                        <h4
                          className={classNames(
                            projectcss.all,
                            projectcss.h4,
                            projectcss.__wab_text,
                            sty.h4__dcgId
                          )}
                        >
                          {"AI Trading Analysis & DeFi Copytrade"}
                        </h4>
                        <h6
                          className={classNames(
                            projectcss.all,
                            projectcss.h6,
                            projectcss.__wab_text,
                            sty.h6__nLtk3
                          )}
                        >
                          {
                            "Leverage cutting-edge AI tools for trading analysis and copy the successful strategies of experienced traders to maximize your gains in the DeFi market.\n"
                          }
                        </h6>
                      </Stack__>
                    </Stack__>
                  </Stack__>
                </Reveal>
              </Stack__>
            </div>
          </section>
          <section className={classNames(projectcss.all, sty.section__vxmSq)}>
            <h1
              className={classNames(
                projectcss.all,
                projectcss.h1,
                projectcss.__wab_text,
                sty.h1__wgSpk
              )}
            >
              {"Our Partner"}
            </h1>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__cvZqd)}
            >
              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__uLla)}
                displayHeight={"auto"}
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"auto"}
                loading={"lazy"}
                src={{
                  src: "/plasmic/otterworld/images/placeholderLogo1Png.png",
                  fullWidth: 260,
                  fullHeight: 123,
                  aspectRatio: undefined
                }}
              />

              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__pG1Wo)}
                displayHeight={"auto"}
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"auto"}
                loading={"lazy"}
                src={{
                  src: "/plasmic/otterworld/images/placeholderLogo1Png.png",
                  fullWidth: 260,
                  fullHeight: 123,
                  aspectRatio: undefined
                }}
              />

              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__gfbMw)}
                displayHeight={"auto"}
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"auto"}
                loading={"lazy"}
                src={{
                  src: "/plasmic/otterworld/images/placeholderLogo1Png.png",
                  fullWidth: 260,
                  fullHeight: 123,
                  aspectRatio: undefined
                }}
              />

              <PlasmicImg__
                alt={""}
                className={classNames(sty.img___7I2B)}
                displayHeight={"auto"}
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"auto"}
                loading={"lazy"}
                src={{
                  src: "/plasmic/otterworld/images/placeholderLogo1Png.png",
                  fullWidth: 260,
                  fullHeight: 123,
                  aspectRatio: undefined
                }}
              />
            </Stack__>
          </section>
          <section className={classNames(projectcss.all, sty.section__rAa1L)}>
            <div className={classNames(projectcss.all, sty.freeBox__lBXqY)}>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__vbJ7Y)}
              >
                <h1
                  className={classNames(
                    projectcss.all,
                    projectcss.h1,
                    projectcss.__wab_text,
                    sty.h1__zfB
                  )}
                >
                  {"Embark on Your DeFi Journey Today"}
                </h1>
                <h6
                  className={classNames(
                    projectcss.all,
                    projectcss.h6,
                    projectcss.__wab_text,
                    sty.h6__zUdl4
                  )}
                >
                  {
                    "Otter World empowers your digital journey with seamless DeFi tools and a strong community. Join us and experience innovation in decentralized finance."
                  }
                </h6>
              </Stack__>
            </div>
            <PlasmicImg__
              alt={""}
              className={classNames(sty.img__cgVjr)}
              displayHeight={"auto"}
              displayMaxHeight={"none"}
              displayMaxWidth={"100%"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"500px"}
              loading={"lazy"}
              src={{
                src: "/plasmic/otterworld/images/mockup2Croppng.png",
                fullWidth: 1000,
                fullHeight: 1000,
                aspectRatio: undefined
              }}
            />
          </section>
          <section className={classNames(projectcss.all, sty.section__vveD9)}>
            <div className={classNames(projectcss.all, sty.columns__fawW1)}>
              <div className={classNames(projectcss.all, sty.column__mJW)}>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__yavvI)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"200px"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/otterworld/images/textOtterworldpng.png",
                    fullWidth: 4000,
                    fullHeight: 2667,
                    aspectRatio: undefined
                  }}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__oz4Jv
                  )}
                >
                  {
                    "Otter World is a comprehensive DeFi platform integrating cutting-edge technology "
                  }
                </div>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__z962B)}
                >
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      sty.link__ucPmI
                    )}
                    component={Link}
                    platform={"nextjs"}
                  >
                    <Twitter2SvgrepoComsvgIcon
                      className={classNames(projectcss.all, sty.svg__xsOnI)}
                      role={"img"}
                    />
                  </PlasmicLink__>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      sty.link__uaGmN
                    )}
                    component={Link}
                    platform={"nextjs"}
                  >
                    <TelegramSvgrepoComsvgIcon
                      className={classNames(projectcss.all, sty.svg___4PNqK)}
                      role={"img"}
                    />
                  </PlasmicLink__>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      sty.link__cNWkC
                    )}
                    component={Link}
                    platform={"nextjs"}
                  >
                    <GitbookSvgrepoComsvgIcon
                      className={classNames(projectcss.all, sty.svg__zTvN)}
                      role={"img"}
                    />
                  </PlasmicLink__>
                </Stack__>
              </div>
              <div className={classNames(projectcss.all, sty.column___0HtGc)} />

              <div className={classNames(projectcss.all, sty.column__nndYs)}>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__vGnpw)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/otterworld/images/buttonappspng.png",
                    fullWidth: 1170,
                    fullHeight: 360,
                    aspectRatio: undefined
                  }}
                />
              </div>
            </div>
          </section>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "pageMetadataOverride", "navigationBar", "h5", "h2"],
  pageMetadataOverride: ["pageMetadataOverride"],
  navigationBar: ["navigationBar"],
  h5: ["h5"],
  h2: ["h2"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  pageMetadataOverride: typeof PlasmicHead;
  navigationBar: typeof NavigationBar;
  h5: "h5";
  h2: "h2";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicHomepage__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicHomepage__VariantsArgs;
    args?: PlasmicHomepage__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicHomepage__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicHomepage__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicHomepage__ArgProps,
          internalVariantPropNames: PlasmicHomepage__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomepage";
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    pageMetadataOverride: makeNodeComponent("pageMetadataOverride"),
    navigationBar: makeNodeComponent("navigationBar"),
    h5: makeNodeComponent("h5"),
    h2: makeNodeComponent("h2"),

    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicHomepage;
/* prettier-ignore-end */
